fat_free_crm/config/routes.rb
Rails.application.routes.draw do
  resources :lists

  root :to => 'home#index'

  match 'activities' => 'home#index'
  match 'admin'      => 'admin/users#index',       :as => :admin
  match 'login'      => 'authentications#new',     :as => :login
  match 'logout'     => 'authentications#destroy', :as => :logout
  match 'profile'    => 'users#show',              :as => :profile
  match 'signup'     => 'users#new',               :as => :signup

  match '/home/options',  :as => :options
  match '/home/toggle',   :as => :toggle
  match '/home/timeline', :as => :timeline
  match '/home/timezone', :as => :timezone
  match '/home/redraw',   :as => :redraw

  resource  :authentication
  resources :comments
  resources :emails
  resources :passwords

  resources :accounts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
      get :opportunities
    end
  end

  resources :campaigns, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :leads
      get :opportunities
    end
  end

  resources :contacts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      get  :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put  :attach
      put  :promote
      put  :reject
    end

    get :autocomplete_account_name, :on => :collection
  end

  resources :opportunities, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
    end
  end

  resources :tasks, :id => /\d+/ do
    collection do
      post :filter
      post :auto_complete
    end
    member do
      put :complete
    end
  end

  resources :users, :id => /\d+/ do
    member do
      get :avatar
      get :password
      put :upload_avatar
      put :change_password
      post :redraw
    end

    collection do
      match :auto_complete
    end
    collection do
      get :opportunities_overview
    end
  end

  namespace :admin do
    resources :groups

    resources :users do
      collection do
        post :auto_complete
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, :except => :index do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        post :auto_complete
        get :options
        post :redraw
        post :sort
        get :subform
      end
    end

    resources :tags do
      member do
        get :confirm
      end
    end

    resources :fields, :as => :custom_fields
    resources :fields, :as => :core_fields

    resources :settings
    resources :plugins
  end

  get '/:controller/tagged/:id' => '#tagged'
end

fat_free_crm/app/models/fields/field_group.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

# == Schema Information
#
# Table name: field_groups
#
#  id         :integer         not null, primary key
#  name       :string(64)
#  label      :string(128)
#  position   :integer
#  hint       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  tag_id     :integer
#  klass_name :string(32)
#

class FieldGroup < ActiveRecord::Base
  has_many :fields, :order => :position
  belongs_to :tag
  before_destroy :not_default_field_group, :move_fields_to_default_field_group

  validates_presence_of :label

  before_save do
    self.name = label.downcase.gsub(/[^a-z0-9]+/, '_') if name.blank? and label.present?
  end

  def key
    "field_group_#{id}"
  end

  def klass
    klass_name.constantize
  end

  def self.with_tags(tag_ids)
    where 'tag_id IS NULL OR tag_id IN (?)', tag_ids
  end

  def label_i18n
    I18n.t(name, :default => label)
  end
  
  private
  # Can't delete default field group
  def not_default_field_group
    name != "custom_fields"
  end
  
  # When deleted, transfer fields to default field group
  def move_fields_to_default_field_group
    default_group = FieldGroup.find_by_name_and_klass_name("custom_fields", klass_name)
    default_group.fields << fields
    self.reload
  end
end

fat_free_crm/app/controllers/admin/field_groups_controller.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

class Admin::FieldGroupsController < Admin::ApplicationController

  helper 'admin/fields'

  # GET /admin/field_groups/new
  # GET /admin/field_groups/new.xml                                        AJAX
  #----------------------------------------------------------------------------
  def new
    @field_group = FieldGroup.new(:klass_name => params[:klass_name])

    respond_with(@field_group)
  end

  # GET /admin/field_groups/1/edit                                         AJAX
  #----------------------------------------------------------------------------
  def edit
    @field_group = FieldGroup.find(params[:id])

    if params[:previous].to_s =~ /(\d+)\z/
      @previous = FieldGroup.find_by_id($1) || $1.to_i
    end

    respond_with(@field_group)
  end

  # POST /admin/field_groups
  # POST /admin/field_groups.xml                                           AJAX
  #----------------------------------------------------------------------------
  def create
    @field_group = FieldGroup.create(params[:field_group])

    respond_with(@field_group)
  end

  # PUT /admin/field_groups/1
  # PUT /admin/field_groups/1.xml                                          AJAX
  #----------------------------------------------------------------------------
  def update
    @field_group = FieldGroup.find(params[:id])
    @field_group.update_attributes(params[:field_group])

    respond_with(@field_group)
  end

  # DELETE /admin/field_groups/1
  # DELETE /admin/field_groups/1.xml                                       AJAX
  #----------------------------------------------------------------------------
  def destroy
    @field_group = FieldGroup.find(params[:id])
    @field_group.destroy

    respond_with(@field_group)
  end

  # POST /admin/field_groups/sort
  #----------------------------------------------------------------------------
  def sort
    asset = params[:asset]
    field_group_ids = params["#{asset}_field_groups"]

    field_group_ids.each_with_index do |id, index|
      FieldGroup.update_all({:position => index+1}, {:id => id})
    end

    render :nothing => true
  end

  # GET /admin/field_groups/1/confirm                                      AJAX
  #----------------------------------------------------------------------------
  def confirm
    @field_group = FieldGroup.find(params[:id])
  end
end

fat_free_crm/app/helpers/admin/field_groups_helper.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

module Admin::FieldGroupsHelper
  def field_group_subtitle(field_group)
    asset = field_group.klass_name.downcase
    html = t(field_group.name, :default => field_group.label)
    html << content_tag(:small, :id => "#{asset}_field_group_#{field_group.id}_intro") do
      if field_group.tag_id
        t(:field_group_tag_restriction, :assets => asset.pluralize, :tag => field_group.tag.try(:name))
      else
        t(:field_group_unrestricted, :assets => asset.pluralize)
      end
    end
    html.html_safe
  end
  
  def link_to_confirm(field_group)
    link_to(t(:delete) + "?", confirm_admin_field_group_path(field_group), :method => :get, :remote => true)
  end

end

fat_free_crm/app/views/admin/field_groups/_confirm.html.haml
.confirm[@field_group, :confirm]
  #{t :field_group_confirm_delete}
  #{t :delete} <b>#{@field_group.name}</b>?
  = link_to_confirm_delete(@field_group) << " : "
  = link_to_function(t(:no_button), "crm.flick('#{dom_id(@field_group, :confirm)}', 'remove')")

fat_free_crm/app/views/admin/field_groups/_edit.html.haml
= form_for([:admin, @field_group], :html => one_submit_only(:field_group), :remote => true) do |f|
  = link_to_close edit_admin_field_group_path(@field_group)
  = f.error_messages
  = render :partial => "top_section", :locals => { :f => f, :edit => true }
  .buttonbar
    = f.submit t(:save_field_group), :id => :field_group_submit
    or
    = link_to_cancel edit_admin_field_group_path(@field_group)

fat_free_crm/app/views/admin/field_groups/_field_group.html.haml
- asset = field_group.klass_name.downcase

.field_group[field_group]
  - edit_form_id = dom_id(field_group, :edit)
  - create_form_id = dom_id(field_group, :create_field)

  .subtitle_tools
    - unless field_group.name == "custom_fields"
      = link_to_inline(edit_form_id, edit_admin_field_group_path(field_group), :text => t(:edit_field_group))
      |
    = link_to(arrow_for(create_form_id) + t(:create_field), '#', :class => 'create')
    - unless field_group.name == "custom_fields"
      |
      = link_to_confirm(field_group)

  .subtitle{ :id => "#{dom_id(field_group)}_title" }= field_group_subtitle(field_group)

  .remote{ hidden.merge(:id => edit_form_id) }

  .list{ :id => dom_id(field_group, :fields) }
    - if (fields = field_group.fields.without_pairs).present?
      = render :partial => "admin/fields/field", :collection => fields
    - else
      .empty{:id => "empty_#{asset}_field_group_#{field_group.id}"}
        = t(:field_group_empty)
        = link_to t(:create_field), '#', :class => 'create', 'data-for' => create_form_id

    .remote{ hidden.merge(:id => create_form_id, :class => 'create_field') }
      = render :partial => 'admin/fields/form', :locals => {:field_group_id => field_group.id}

fat_free_crm/app/views/admin/field_groups/_new.html.haml
- path = new_admin_field_group_path(:klass_name => @field_group.klass_name)

= form_for([:admin, @field_group], :html => one_submit_only(:field_group), :remote => true) do |f|
  = link_to_close path
  = f.error_messages
  = render :partial => "top_section", :locals => { :f => f }
  .buttonbar
    = f.submit t(:create_field_group), :id => :field_group_submit
    or
    = link_to_cancel path

fat_free_crm/app/views/admin/field_groups/_top_section.html.haml
.section
  = f.hidden_field :klass_name

  %table{:style => 'width:auto;'}
    %tr
      %td
        .label.top.req= t(:label) + ":"
        = f.text_field :label
      %td= spacer
      %td
        .label.top
          =t(:restrict_by_tag)
          %small= t(:restrict_by_tag_info, :assets => f.object.klass_name.downcase.pluralize)
        = f.select :tag_id, Tag.all.map { |tag| [tag.name, tag.id] }, :include_blank => true