fat_free_crm/config/routes.rb
Rails.application.routes.draw do
  resources :lists

  root :to => 'home#index'

  match 'activities' => 'home#index'
  match 'admin'      => 'admin/users#index',       :as => :admin
  match 'login'      => 'authentications#new',     :as => :login
  match 'logout'     => 'authentications#destroy', :as => :logout
  match 'profile'    => 'users#show',              :as => :profile
  match 'signup'     => 'users#new',               :as => :signup

  match '/home/options',  :as => :options
  match '/home/toggle',   :as => :toggle
  match '/home/timeline', :as => :timeline
  match '/home/timezone', :as => :timezone
  match '/home/redraw',   :as => :redraw

  resource  :authentication
  resources :comments
  resources :emails
  resources :passwords

  resources :accounts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
      get :opportunities
    end
  end

  resources :campaigns, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :leads
      get :opportunities
    end
  end

  resources :contacts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      get  :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put  :attach
      put  :promote
      put  :reject
    end

    get :autocomplete_account_name, :on => :collection
  end

  resources :opportunities, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
    end
  end

  resources :tasks, :id => /\d+/ do
    collection do
      post :filter
      post :auto_complete
    end
    member do
      put :complete
    end
  end

  resources :users, :id => /\d+/ do
    member do
      get :avatar
      get :password
      put :upload_avatar
      put :change_password
      post :redraw
    end

    collection do
      match :auto_complete
    end
    collection do
      get :opportunities_overview
    end
  end

  namespace :admin do
    resources :groups

    resources :users do
      collection do
        post :auto_complete
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, :except => :index do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        post :auto_complete
        get :options
        post :redraw
        post :sort
        get :subform
      end
    end

    resources :tags do
      member do
        get :confirm
      end
    end

    resources :fields, :as => :custom_fields
    resources :fields, :as => :core_fields

    resources :settings
    resources :plugins
  end

  get '/:controller/tagged/:id' => '#tagged'
end

fat_free_crm/app/controllers/home_controller.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

class HomeController < ApplicationController
  before_filter :require_user, :except => [ :toggle, :timezone ]
  before_filter :set_current_tab, :only => :index
  before_filter "hook(:home_before_filter, self, :amazing => true)"

  #----------------------------------------------------------------------------
  def index
    @hello = "Hello world" # The hook below can access controller's instance variables.
    hook(:home_controller, self, :params => "it works!")

    @activities = get_activities
    @my_tasks = Task.visible_on_dashboard(current_user).by_due_at
    @my_opportunities = Opportunity.visible_on_dashboard(current_user).by_closes_on.by_amount
    @my_accounts = Account.visible_on_dashboard(current_user).by_name
    respond_with(@activities)
  end

  # GET /home/options                                                      AJAX
  #----------------------------------------------------------------------------
  def options
    unless params[:cancel].true?
      @asset = current_user.pref[:activity_asset] || "all"
      @action = current_user.pref[:activity_event] || "all_events"
      @user = current_user.pref[:activity_user] || "all_users"
      @duration = current_user.pref[:activity_duration] || "two_days"
      @all_users = User.order("first_name, last_name")
    end
  end

  # POST /home/redraw                                                      AJAX
  #----------------------------------------------------------------------------
  def redraw
    current_user.pref[:activity_asset] = params[:asset] if params[:asset]
    current_user.pref[:activity_event] = params[:event] if params[:event]
    current_user.pref[:activity_user] = params[:user] if params[:user]
    current_user.pref[:activity_duration] = params[:duration] if params[:duration]

    @activities = get_activities
    render :index
  end

  # GET /home/toggle                                                       AJAX
  #----------------------------------------------------------------------------
  def toggle
    if session[params[:id].to_sym]
      session.delete(params[:id].to_sym)
    else
      session[params[:id].to_sym] = true
    end
    render :nothing => true
  end

  # GET /home/timeline                                                     AJAX
  #----------------------------------------------------------------------------
  def timeline
    unless params[:type].empty?
      model = params[:type].camelize.constantize
      item = model.find(params[:id])
      item.update_attribute(:state, params[:state])
    else
      comments, emails = params[:id].split("+")
      Comment.update_all("state = '#{params[:state]}'", "id IN (#{comments})") unless comments.blank?
      Email.update_all("state = '#{params[:state]}'", "id IN (#{emails})") unless emails.blank?
    end

    render :nothing => true
  end

  # GET /home/timezone                                                     AJAX
  #----------------------------------------------------------------------------
  def timezone
    #
    # (new Date()).getTimezoneOffset() in JavaScript returns (UTC - localtime) in
    # minutes, while ActiveSupport::TimeZone expects (localtime - UTC) in seconds.
    #
    if params[:offset]
      session[:timezone_offset] = params[:offset].to_i * -60
      ActiveSupport::TimeZone[session[:timezone_offset]]
    end
    render :nothing => true
  end

  private
  #----------------------------------------------------------------------------
  def get_activities(options = {})
    options[:asset]    ||= activity_asset
    options[:event]    ||= activity_event
    options[:user]     ||= activity_user
    options[:duration] ||= activity_duration
    options[:max]      ||= 500

    Version.latest(options).visible_to(current_user)
  end

  #----------------------------------------------------------------------------
  def activity_asset
    asset = current_user.pref[:activity_asset]
    if asset.nil? || asset == "all"
      nil
    else
      asset.singularize.capitalize
    end
  end

  #----------------------------------------------------------------------------
  def activity_event
    event = current_user.pref[:activity_event]
    if event == "all_events"
      %w(create update destroy)
    else
      event
    end
  end

  #----------------------------------------------------------------------------
  def activity_user
    user = current_user.pref[:activity_user]
    if user && user != "all_users"
      user = if user =~ /@/ # email
          User.where(:email => user).first
        else # first_name middle_name last_name any_name
          name_query = if user.include?(" ")
            user.name_permutations.map{ |first, last|
              "(upper(first_name) LIKE upper('%#{first}%') AND upper(last_name) LIKE upper('%#{last}%'))"
            }.join(" OR ")
          else
            "upper(first_name) LIKE upper('%#{user}%') OR upper(last_name) LIKE upper('%#{user}%')"
          end
          User.where(name_query).first
        end
    end
    user.is_a?(User) ? user.id : nil
  end

  #----------------------------------------------------------------------------
  def activity_duration
    duration = current_user.pref[:activity_duration]
    if duration
      words = duration.split("_") # "two_weeks" => 2.weeks
      if %w(one two).include?(words.first)
        %w(zero one two).index(words.first).send(words.last)
      end
    end
  end

end

fat_free_crm/app/helpers/home_helper.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

module HomeHelper
  def sort_by_assets
    Version::ASSETS.map do |asset|
      %Q[{ name: "#{t(asset.singularize)}", on_select: function() { #{redraw(:asset, [ asset, t(asset.singularize).downcase ], url_for(:action => :redraw))} } }]
    end
  end

  #----------------------------------------------------------------------------
  def sort_by_events
    Version::EVENTS.map do |event|
      %Q[{ name: "#{t(event + '_past_participle')}", on_select: function() { #{redraw(:event, [ event, t(event + '_past_participle').downcase ], url_for(:action => :redraw))} } }]
    end
  end

  #----------------------------------------------------------------------------
  def sort_by_duration
    Version::DURATION.map do |duration|
      %Q[{ name: "#{t(duration)}", on_select: function() { #{redraw(:duration, [ duration, t(duration).downcase ], url_for(:action => :redraw))} } }]
    end
  end

  #----------------------------------------------------------------------------
  def sort_by_users
    users = [[ "all_users", t(:option_all_users) ]] + @all_users.map do |user|
      escaped = escape_javascript(user.full_name)
      [ escaped, escaped ]
    end

    users.map do |key, value|
      %Q[{ name: "#{value}", on_select: function() { #{redraw(:user, [ key, (value == t(:option_all_users) ? value.downcase : value) ], url_for(:action => :redraw))} } }]
    end
  end

  # Activity title for RSS/ATOM feeds.
  #----------------------------------------------------------------------------
  def activity_title(activity)
    user    = activity.user.full_name
    action  = t('action_' + activity.event)
    type    = t('subject_' + activity.item_type.downcase)
    subject = if item = activity.item
      if item.respond_to?(:full_name)
        item.full_name
      elsif item.respond_to?(:name)
        item.name
      end
    end
    t(:activity_text, :user => user, :action => action, :type => type, :subject => subject,
      :default => "#{user} #{action} #{type} #{subject}")
  end

  # Displays 'not showing' message for a given count, entity and limit
  def show_hidden_entities_message(count, entity, limit = 10)
    if count > limit
      hidden_count = count - 10
      entity_string = I18n.t("#{hidden_count == 1 ? entity : entity.pluralize}_small")
      content_tag(:p) do
        t(:not_showing_hidden_entities, :entity => entity_string, :count => hidden_count)
      end
    end
  end
end

fat_free_crm/app/views/home/_account.html.haml
- amount = account.opportunities.not_lost.map(&:weighted_amount).sum
%li.highlight[account]
  - if account.category
    .strip{:class => account.category} #{t(account.category)}
  - else
    .strip{:style => "color: gray;"} #{t :other}

  .indent
    = link_to(h(account.name), account)
    &ndash;
    %tt
      = account.location << ", " unless account.location.blank?
      - user_name = account.user_id == current_user.id ? t(:me) : account.user.try(:full_name)
      - if user_name
        = t(:added_by, :time_ago => time_ago_in_words(account.created_at), :user => user_name)
      - else
        = t(:added_ago, :value => time_ago_in_words(account.created_at))

    - unless current_user.preference[:accounts_index_view] == "accounts_index_brief"
      %dt
        = link_to(account.website, account.website.to_url) << " | " if account.website.present?
        = link_to_email(account.email) << " | " if account.email.present?
        = t(:phone_small) << ": " << (account.toll_free_phone || account.phone) << " | " if account.toll_free_phone? || account.phone?
        = t('pluralize.contact', account.contacts.count) << " | "
        = t('pluralize.opportunity', account.opportunities.count)
      - if account.tag_list.present?
        %dt
          .tags= tags_for_dashboard(account)
      = hook(:account_bottom, self, :account => account)

fat_free_crm/app/views/home/_activity.html.haml
- user = link_to(h(activity.user.full_name), user_path(activity.user)) if activity.user

- subject = if (item = activity.related || activity.item)
  - if item.respond_to?(:full_name)
    - link_to item.full_name, polymorphic_url(item)

  - elsif [Account, Campaign, Contact, Lead, Opportunity].include?(item.class)
    - link_to item.name, polymorphic_url(item)

  - elsif item.respond_to?(:name)
    - content_tag :span, item.name, :style => "color:black;" # Individual tasks have no landing pages where we could link to.

- known_event = t('action_' + activity.event, :default => 0) != 0

- if (user.present? && subject.present?) || !known_event
  %li[activity]
    .tools
      %small
        = l(activity.created_at, :format => :short)
    %tt
      - if known_event
        - action = t('action_' + activity.event)
        - type = t('subject_' + activity.item_type.downcase)
        = link_to avatar_for(activity.user, :size => :thumb), user_path(activity.user)
        = t("activity_text", :user => user, :action => action, :type => type, :subject => subject, :default => "#{user} #{action} #{type} #{subject}").html_safe # locales optionally can change the word order for activities using 'activity_text'
        - if ((item = activity.item).class == Comment) and Setting.comments_visible_on_dashboard
          = t('action_create_comment', :comment => truncate(h(item.comment), :length => 90)).html_safe
      - else
        - type = t(activity.item_type.downcase)
        - if item.respond_to? :email
          = avatar_for(item, :size => "16x16")
        = "#{type} #{subject}:".html_safe
        = auto_link(t(activity.event)).html_safe

fat_free_crm/app/views/home/_assets_menu.html.haml
:plain
  new crm.Menu({
    trigger   : "asset",
    fade      : 0.5,
    appear    : 0.5,
    menu_items: [ #{sort_by_assets.join(",")} ]
  });

fat_free_crm/app/views/home/_duration_menu.html.haml
:plain
  new crm.Menu({
    trigger   : "duration",
    fade      : 0.5,
    appear    : 0.5,
    width     : 165,
    menu_items: [ #{sort_by_duration.join(",")} ]
  });

fat_free_crm/app/views/home/_events_menu.html.haml
:plain
  new crm.Menu({
    trigger   : "event",
    fade      : 0.5,
    appear    : 0.5,
    menu_items: [ #{sort_by_events.join(",")} ]
  });

fat_free_crm/app/views/home/_opportunity.html.haml
%li.highlight[opportunity]
  - if opportunity.stage
    .strip{:class => opportunity.stage}= t(opportunity.stage)
  - else
    .strip.white #{t :other}

  .indent
    = link_to(h(opportunity.name), opportunity)
    - if opportunity.account
      == #{t :from} #{link_to(h(opportunity.account.name), account_path(opportunity.account))}
    %tt
      &ndash;
      - user_name = opportunity.user_id == current_user.id ? t(:me) : opportunity.user.try(:full_name)
      - if user_name
        = t(:added_by, :time_ago => time_ago_in_words(opportunity.created_at), :user => user_name)
      - else
        = t(:added_ago, :value => time_ago_in_words(opportunity.created_at))
    - unless current_user.preference[:opportunities_index_view] == "opportunities_index_brief"
      %dt
        %b= number_to_currency(opportunity.weighted_amount, :precision => 0) + " | "
        - won_or_lost = %w(won lost).include?(opportunity.stage)
        - unless won_or_lost
          = t(:probability_number, (opportunity.probability || 0).to_s + '%') + " | "
        - if opportunity.closes_on
          - if won_or_lost
            - if opportunity.closes_on >= Date.today
              = t(:closing_date, l(opportunity.closes_on, :format => :mmddyy))
            - else
              = t(:closed_ago_on, :time_ago => distance_of_time_in_words(opportunity.closes_on, Date.today), :date => l(opportunity.closes_on, :format => :mmddyy))
          - elsif opportunity.closes_on > Date.today
            = t(:expected_to_close,  :time => distance_of_time_in_words(Date.today, opportunity.closes_on), :date => l(opportunity.closes_on, :format => :mmddyy))
          - elsif opportunity.closes_on == Date.today
            %span.warn= t(:closes_today)
          - else
            %span.warn= t(:past_due, distance_of_time_in_words(opportunity.closes_on, Date.today))
        - else
          = t(:no_closing_date)
      - if opportunity.tag_list.present?
        %dt
          .tags= tags_for_dashboard(opportunity)
      = hook(:opportunity_bottom, self, :opportunity => opportunity)

fat_free_crm/app/views/home/_options.html.haml
%p
  = link_to_close url_for(:action => "options")
  = hidden_field_tag "account[user_id]", current_user.id

  -# activity_options: Show %{models} %{action_type} performed by %{user} in the past %{period}
  = t(:activity_options, :models => link_to(t(@asset).singularize.downcase, "#", :id => :asset), :action_type => link_to(t(@action + "_past_participle").downcase, "#", :id => :event), :user => link_to(t(@user), "#", :id => :user), :period => link_to(t(@duration).downcase, "#", :id => :duration)).html_safe
%p

%script
  = render "assets_menu"
  = render "events_menu"
  = render "users_menu"
  = render "duration_menu"

fat_free_crm/app/views/home/_task.html.haml
%li.highlight[task]
  - unless task.category.blank?
    .strip{:class => task.category}= t(task.category)
  - else
    .strip.white #{t :other}
  .indent
    %label{ :id => dom_id(task, :name) }
      - if task.user.id != current_user.id
        = t(:task_from, link_to(task.user.full_name, user_path(task.user))).html_safe << ':'
      = link_to(h(task.name), tasks_path)
      - if task.asset_id?
        == #{t :related} #{link_to(h(task.asset.name), polymorphic_url(task.asset))}
      &ndash;
    %tt
      - if task.bucket == "due_asap"
        %span.urgent= t(:task_due_now)

      - elsif task.bucket == "due_later"
        = t(:task_due_later)

      - else
        - if task.at_specific_time?
          - if task.due_at < Time.now
            %span.warn
              = distance_of_time_in_words(task.due_at, Time.now)
              = t(:task_overdue)
              = l(task.due_at.localtime, :format => :mmddhhss)
          - else
            = t(:task_due_in, distance_of_time_in_words(Time.now, task.due_at))
            = '(' << l(task.due_at.localtime, :format => :mmddhhss) << ')'

        - else
          - if task.due_at < Date.today
            %span.warn
              = distance_of_time_in_words(task.due_at, Time.now)
              = t(:task_overdue)
              = l(task.due_at.localtime.to_date, :format => :mmdd)
          - elsif task.due_at > Date.today
            = t(:task_due_in, distance_of_time_in_words(Time.now, task.due_at.localtime.end_of_day))
            = ' (' << l(task.due_at.localtime.to_date, :format => :mmdd) << ')'
          - else
            %span.cool= t(:task_due_today)

    - unless task.background_info.blank?
      %div
        %dt= h(task.background_info)

fat_free_crm/app/views/home/_users_menu.html.haml
:plain
  new crm.Menu({
    trigger   : "user",
    fade      : 0.5,
    appear    : 0.5,
    width     : 180,
    menu_items: [ #{sort_by_users.join(",")} ]
  });

fat_free_crm/app/views/home/index.html.haml
= styles_for :task, :opportunity, :account

.title
  %span#title #{t :my_tasks}
%ul.list#tasks
  - unless @my_tasks.empty?
    = render :partial => "home/task", :collection => @my_tasks.limit(10)
    = show_hidden_entities_message(@my_tasks.count, 'task', 10)
  - else
    #{t :no_task_records}

.title
  %span#title #{t :my_opportunities}
%ul.list#opportunities
  - unless @my_opportunities.empty?
    = render :partial => "home/opportunity", :collection => @my_opportunities.limit(10)
    = show_hidden_entities_message(@my_opportunities.count, 'opportunity', 10)
  - else
    #{t :no_opportunity_records}

.title
  %span#title #{t :my_accounts}
%ul.list#accounts
  - unless @my_accounts.empty?
    = render :partial => "home/account", :collection => @my_accounts.limit(10)
    = show_hidden_entities_message(@my_accounts.count, 'account', 10)
  - else
    #{t :no_account_records}

.title_tools
  = link_to_inline(:options, url_for(:action => :options), :text => t(:options))

.title
  %span#title #{t :recent_activity}
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")
.remote#options{ hidden }

%ul.list#activities
  - unless @activities.empty?
    = render :partial => "activity", :collection => @activities
  - else
    #{t :no_activity_records}


#export= render "shared/export"
/
  Check out HTML source to view the output of the hook if you have sample plugin installed
  http://github.com/michaeldv/crm_sample_plugin/tree/master
  = hook(:home_view, self, :hello => "world!", :welcome => "home")