fat_free_crm/config/routes.rb
Rails.application.routes.draw do
  resources :lists

  root :to => 'home#index'

  match 'activities' => 'home#index'
  match 'admin'      => 'admin/users#index',       :as => :admin
  match 'login'      => 'authentications#new',     :as => :login
  match 'logout'     => 'authentications#destroy', :as => :logout
  match 'profile'    => 'users#show',              :as => :profile
  match 'signup'     => 'users#new',               :as => :signup

  match '/home/options',  :as => :options
  match '/home/toggle',   :as => :toggle
  match '/home/timeline', :as => :timeline
  match '/home/timezone', :as => :timezone
  match '/home/redraw',   :as => :redraw

  resource  :authentication
  resources :comments
  resources :emails
  resources :passwords

  resources :accounts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
      get :opportunities
    end
  end

  resources :campaigns, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :leads
      get :opportunities
    end
  end

  resources :contacts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      get  :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put  :attach
      put  :promote
      put  :reject
    end

    get :autocomplete_account_name, :on => :collection
  end

  resources :opportunities, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      post :auto_complete
      post :redraw
      get :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
    end
  end

  resources :tasks, :id => /\d+/ do
    collection do
      post :filter
      post :auto_complete
    end
    member do
      put :complete
    end
  end

  resources :users, :id => /\d+/ do
    member do
      get :avatar
      get :password
      put :upload_avatar
      put :change_password
      post :redraw
    end

    collection do
      match :auto_complete
    end
    collection do
      get :opportunities_overview
    end
  end

  namespace :admin do
    resources :groups

    resources :users do
      collection do
        post :auto_complete
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, :except => :index do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        post :auto_complete
        get :options
        post :redraw
        post :sort
        get :subform
      end
    end

    resources :tags do
      member do
        get :confirm
      end
    end

    resources :fields, :as => :custom_fields
    resources :fields, :as => :core_fields

    resources :settings
    resources :plugins
  end

  get '/:controller/tagged/:id' => '#tagged'
end

fat_free_crm/app/models/fields/core_field.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

# == Schema Information
#
# Table name: fields
#
#  id             :integer         not null, primary key
#  type           :string(255)
#  field_group_id :integer
#  position       :integer
#  name           :string(64)
#  label          :string(128)
#  hint           :string(255)
#  placeholder    :string(255)
#  as             :string(32)
#  collection     :text
#  disabled       :boolean
#  required       :boolean
#  maxlength      :integer
#  created_at     :datetime
#  updated_at     :datetime
#

class CoreField < Field
  # Some CoreField attributes should be read-only
  attr_readonly :name, :as, :collection
  before_destroy :error_on_destroy

  def error_on_destroy
    errors.add_to_base "Core fields cannot be deleted."
  end
end

fat_free_crm/app/models/fields/custom_field_date_pair.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

class CustomFieldDatePair < CustomFieldPair

  # Register this CustomField with the application
  #------------------------------------------------------------------------------
  register(:as => 'date_pair', :klass => 'CustomFieldDatePair', :type => 'date')

  # For rendering paired values
  # Handle case where both pairs are blank
  #------------------------------------------------------------------------------
  def render_value(object)
    return "" unless paired_with.present?
    from = render(object.send(name))
    to = render(object.send(paired_with.name))
    if from.present? and to.present?
      I18n.t('pair.from_to', :from => from, :to => to)
    elsif from.present? and !to.present?
      I18n.t('pair.from_only', :from => from)
    elsif !from.present? and to.present?
      I18n.t('pair.to_only', :to => to)
    else
      ""
    end
  end
  
  def render(value)
    value && value.strftime(I18n.t("date.formats.mmddyy"))
  end
  
  def custom_validator(obj)
    super
    # validate when we get to 2nd of the pair
    if pair_id.present?
      start = CustomFieldPair.find(pair_id)
      return if start.nil?
      from = obj.send(start.name)
      to = obj.send(name)
      obj.errors.add(name.to_sym, ::I18n.t('activerecord.errors.models.custom_field.endbeforestart', :field => start.label)) if from.present? and to.present? and (from > to)
    end
  end

end

fat_free_crm/app/models/fields/custom_field_datetime_pair.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

class CustomFieldDatetimePair < CustomFieldDatePair

  # Register this CustomField with the application
  #------------------------------------------------------------------------------
  register(:as => 'datetime_pair', :klass => 'CustomFieldDatetimePair', :type => 'timestamp')

  def render(value)
    value && value.strftime(I18n.t("time.formats.mmddhhss"))
  end

end

fat_free_crm/app/models/fields/custom_field_pair.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

class CustomFieldPair < CustomField

  has_one :pair, :class_name => CustomFieldPair, :foreign_key => 'pair_id', :dependent => :destroy # points to 'end'

  # Helper to create a pair. Used in fields_controller
  #------------------------------------------------------------------------------
  def self.create_pair(params)
    fields = params['field']
    as = params['field']['as']
    pair = params.delete('pair')
    base_params = fields.delete_if{|k,v| !%w(field_group_id label as).include?(k)}
    klass = ("custom_field_" + as.gsub('pair', '_pair')).classify.constantize
    field1 = klass.create( base_params.merge(pair['0']) )
    field2 = klass.create( base_params.merge(pair['1']).merge('pair_id' => field1.id, 'required' => field1.required, 'disabled' => field1.disabled) )
    [field1, field2]
  end
  
  # Helper to update a pair. Used in fields_controller
  #------------------------------------------------------------------------------
  def self.update_pair(params)
    fields = params['field']
    pair = params.delete('pair')
    base_params = fields.delete_if{|k,v| !%w(field_group_id label as).include?(k)}
    field1 = CustomFieldPair.find(params['id'])
    field1.update_attributes( base_params.merge(pair['0']) )
    field2 = field1.paired_with
    field2.update_attributes( base_params.merge(pair['1']).merge('required' => field1.required, 'disabled' => field1.disabled) )
    [field1, field2]
  end

  # Returns the field that this field is paired with
  #------------------------------------------------------------------------------
  def paired_with
    pair || CustomFieldPair.where(:pair_id => id).first
  end

end

fat_free_crm/app/controllers/admin/fields_controller.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

class Admin::FieldsController < Admin::ApplicationController
  before_filter "set_current_tab('admin/fields')", :only => [ :index ]

  load_resource :except => [:create, :subform]

  # GET /fields
  # GET /fields.xml                                                      HTML
  #----------------------------------------------------------------------------
  def index
  end

  # GET /fields/1
  # GET /fields/1.xml                                                    HTML
  #----------------------------------------------------------------------------
  def show
    respond_with(@field)
  end

  # GET /fields/new
  # GET /fields/new.xml                                                  AJAX
  #----------------------------------------------------------------------------
  def new
    @field = Field.new
    respond_with(@field)
  end

  # GET /fields/1/edit                                                   AJAX
  #----------------------------------------------------------------------------
  def edit
    @field = Field.find(params[:id])
    respond_with(@field)    
  end

  # POST /fields
  # POST /fields.xml                                                     AJAX
  #----------------------------------------------------------------------------
  def create
    as = params[:field][:as]
    @field = 
      if as =~ /pair/
        CustomFieldPair.create_pair(params).first
      elsif as.present?
        klass = Field.lookup_class(as).classify.constantize
        klass.create(params[:field])
      else
        Field.new(params[:field]).tap(&:valid?)
      end

    respond_with(@field)

  end

  # PUT /fields/1
  # PUT /fields/1.xml                                                    AJAX
  #----------------------------------------------------------------------------
  def update
    if (params[:field][:as] =~ /pair/)
      @field = CustomFieldPair.update_pair(params).first
    else
      @field = Field.find(params[:id])
      @field.update_attributes(params[:field])
    end

    respond_with(@field)
  end

  # DELETE /fields/1
  # DELETE /fields/1.xml                                        HTML and AJAX
  #----------------------------------------------------------------------------
  def destroy
    @field = Field.find(params[:id])
    @field.destroy

    respond_with(@field)
  end

  # POST /fields/sort
  #----------------------------------------------------------------------------
  def sort
    field_group_id = params[:field_group_id].to_i
    field_ids = params["fields_field_group_#{field_group_id}"] || []

    field_ids.each_with_index do |id, index|
      Field.update_all({:position => index+1, :field_group_id => field_group_id}, {:id => id})
    end

    render :nothing => true
  end
  
  # GET /fields/subform
  #----------------------------------------------------------------------------
  def subform
    field = params[:field]
    as = field[:as]

    @field = if (id = field[:id]).present?
        Field.find(id).tap{|f| f.as = as}
      else
        field_group_id = field[:field_group_id]
        klass = Field.lookup_class(as).classify.constantize
        klass.new(:field_group_id => field_group_id, :as => as)
      end

    respond_with(@field) do |format|
      format.html { render :partial => 'admin/fields/subform' }
    end  
  end
  
end

fat_free_crm/app/helpers/admin/fields_helper.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

module Admin::FieldsHelper

  # Returns the list of :null and :safe database column transitions.
  # Only these options should be shown on the custom field edit form.
  def field_edit_as_options(field = nil)
    # Return every available field_type if no restriction
    options = (field.as.present? ? field.available_as : Field.field_types).keys
    options.map{|k| [t("field_types.#{k}.title"), k] }
  end

  def field_group_options
    FieldGroup.all.map {|fg| [fg.name, fg.id]}
  end
end

fat_free_crm/app/helpers/fields_helper.rb
# Fat Free CRM
# Copyright (C) 2008-2011 by Michael Dvorkin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

module FieldsHelper
end

fat_free_crm/app/views/admin/fields/_field.html.haml
%li.highlight.position{:class => field.class.name.underscore, :id => "field_#{field.id}"}
  %span.handle
    %img( src="/assets/sortable.gif" )

  .tools
    %small
      = link_to t(:edit), edit_admin_field_path(field), :class => 'edit'
      = link_to_delete(field, :url => admin_field_path(field), :klass_name => 'Field')

  %tt
    %b= field.label
    == (#{t("field_types.#{field.as}.title")})

    == added #{time_ago_in_words(field.created_at)} ago
    = hook(:field_bottom, self, :field => field)

  .edit_field

fat_free_crm/app/views/admin/fields/_form.html.haml
- @field ||= CustomField.new
- field_group_id ||= @field.field_group_id
- new_field = @field.id.nil?
- url = new_field ? admin_fields_path : admin_field_path
- html_id = new_field ? nil : "edit_field_#{@field.id}"

%div{:class => new_field ? nil : 'remote edit_field'}
  = form_for([:admin, @field], :url => url, :as => :field, :html => one_submit_only(:field).merge(:class => nil, :id => html_id), :remote => true) do |f|
    = link_to( 'x', '#', :class => 'close', :title => t(:close_form) )
    = f.error_messages
    
    = hidden_field_tag 'field[field_group_id]', field_group_id, :id => nil

    .section
      %table
        %tr
          %td
            .label.top.req Field label:
            = f.text_field :label, :id => nil

          %td= spacer
          %td
            .label.top.req Field type:
            = select :field, :as, field_edit_as_options(@field), :include_blank => true, :id => nil

      .subform
        = render(:partial => 'admin/fields/subform') unless new_field

    .buttonbar
      - if new_field
        = f.submit t(:create_field), :id => :field_submit
      - else
        = f.submit t(:save_field), :id => :field_submit
      or
      = link_to( t(:cancel), '#', :class => 'cancel' )

fat_free_crm/app/views/admin/fields/_sort_by.html.haml
- sort_by_menu_items = ["Field name", "Field label", "Field type", "Table name", "Display sequence", "Display block", "Display width", "Max size"].inject([]) do | items, sort_by|
  - items << %Q[{ name: "#{sort_by}", on_select: function() { #{redraw(:sort_by, sort_by.downcase!)} } }]

:plain
  new crm.Menu({
    trigger   : "sort_by",
    fade      : 0.5,
    appear    : 0.5,
    menu_items: [ #{sort_by_menu_items.join(",")} ]
  });

fat_free_crm/app/views/admin/fields/_subform.html.haml
= fields_for :field, @field do |f|
  - if (as = f.object.as).present? and lookup_context.exists? "#{as}_field", 'admin/custom_fields', true
    = render :partial => "admin/custom_fields/#{as}_field", :locals => {:f => f}
  - else
    = render :partial => "admin/custom_fields/base_field", :locals => {:f => f}

fat_free_crm/app/views/admin/fields/create.js.erb
<% id = "create_field_field_group_#{@field.field_group_id}";
   custom_field_id = "custom_field_#{@field.id}";
   container_id = "fields_field_group_#{@field.field_group_id}";
   create_field_id = "create_field_field_group_#{@field.field_group_id}";
   empty_field_id = "empty_opportunity_field_group_#{@field.field_group_id}"
%>

<% if @field.valid? %>
  jQuery("#<%=id%>_arrow").html(crm.COLLAPSED)
  jQuery('#<%=create_field_id%>').before('<%= j (render :partial => "field", :collection => [@field]) %>')
  jQuery('#<%=create_field_id%>').before('<%= j (sortable_element(container_id, :url => sort_admin_fields_path(:field_group_id => @field.field_group_id))) %>')
  jQuery('#<%=custom_field_id%>').effect("highlight", { duration:1500 });
  jQuery("#<%=create_field_id%>").hide();
  jQuery("#<%=empty_field_id%>").hide();
<% else %>
  jQuery('#<%=id%>').html('<%= j(render :partial => "admin/fields/form", :locals => {:field_group_id => @field.field_group_id} ) %>')
  jQuery('#<%=id%>').effect("shake", { duration:250, distance: 6 });
  jQuery('#<%=id%>').find('input[type="text"]').first().focus()
<% end %>

fat_free_crm/app/views/admin/fields/destroy.js.erb
<% id = "field_#{@field.id}" %>
<% if @field.destroyed? %>
  jQuery('li#<%=id%>').slideUp(250);
<% else %>
  jQuery('li#<%=id%>').effect("shake", { duration:250, distance: 6});
  jQuery('#flash').html('<%=flash[:warning]%>')
  jQuery(crm.flash('warning'))
  <% flash[:warning] = nil %>
<% end %>

fat_free_crm/app/views/admin/fields/edit.js.erb
jQuery('#<%="field_#{@field.id}"%>').find('.edit_field').replaceWith( '<%= j(render :partial => "admin/fields/form") %>' )

fat_free_crm/app/views/admin/fields/index.html.haml
= styles_for :fields

.title
  %span#create_field_title= t(:admin_tab_fields)

.info= t(:admin_fields_info).html_safe

.inline_tabs
  %ul
    - list_of_entities.each do |entity|
      - asset = entity.downcase
      %li{ "data-tab-class" => asset, :class => ("selected" if entity == 'Contact') }
        = link_to t(entity), "#"

- list_of_entities.each do |entity|
  - asset = entity.downcase
  - klass = asset.classify.constantize
  .fields{ :id => "#{asset}_section", :style => ("display: none;" if asset != 'contact') }

    - create_form_id = "#{asset}_create_field_group"

    .title_tools
      = link_to_inline(create_form_id, new_admin_field_group_path(:klass_name => klass.name), :text => t(:create_field_group))

    .title
      = t(asset)

    - container_id = "#{asset}_field_groups"
    .list{ :id => container_id }
      = render :partial => "admin/field_groups/field_group", :collection => klass.field_groups, :locals => {:asset => asset, :klass => klass}

    - group_list_ids = klass.field_groups.map {|field_group| dom_id(field_group, :fields)}
    - klass.field_groups.each do |field_group|
      = sortable_element(dom_id(field_group, :fields), :url => sort_admin_fields_path(:field_group_id => field_group.id), :containment => group_list_ids, :dropOnEmpty => true)

    = sortable_element(container_id, :url => sort_admin_field_groups_path(:asset => asset), :tag => :div)

    .remote{ hidden.merge(:id => create_form_id) }

fat_free_crm/app/views/admin/fields/show.html.haml
= styles_for :field

#confirm{ hidden }
.title_tools#menu
  = link_to_inline(:edit_field, edit_admin_field_path(@field), :text => "Edit") + " | "
.title#edit_field_title= @field.field_label

%div#edit_field{ hidden }

%tt
  %br
  Label:
  %b
    - if @field.field_label?
      = @field.field_label
  %br
  Name:
  %b
    - if @field.field_name?
      = @field.field_name
  %br
  Table:
  %b
    - if @field.table_name?
      = @field.table_name.pluralize
  %br
  Type:
  %b
    - if @field.field_type?
      = @field.field_type
  %br
  %br
  Created at:
  %b
    = @field.created_at.to_s
  %br
  Updated at:
  %b
    = @field.updated_at.to_s

= hook(:show_field_bottom, self)

fat_free_crm/app/views/admin/fields/update.js.erb
<% custom_field_id = "field_#{@field.id}";
   container_id = "#{@field.klass_name.downcase}_field_groups"
%>

<% if @field.errors.empty? %>
  jQuery('#<%=custom_field_id%>').replaceWith('<%= j (render :partial => "field", :collection => [@field]) %>')
  jQuery('#<%=custom_field_id%>').effect("highlight", { duration:1000 });
  jQuery('#<%=container_id%>').after('<%= j (sortable_element(container_id, :url => sort_admin_fields_path(:field_group_id => @field.field_group_id))) %>')
<% else %>
  jQuery('#<%=custom_field_id%>').find('.edit_field').replaceWith('<%= j(render :partial => "form") %>')
  jQuery('#<%=custom_field_id%>').effect("shake", { duration:250, distance: 6 });
  jQuery('#<%=custom_field_id%>').find('input[type="text"]').first().focus()
<% end %>